project_id = "yfzgcndvbibqbmpviogq"

[functions.admin-auth]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.admin-settings]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false
